### PR TITLE
Use flutter_map_dragmarker package, add native example projects

### PR DESCRIPTION
**Pull request by josxha**
This pull request...
- removes `dragmarkers.dart` and uses the functionality from the flutter_map_dragmarker package (currently set to https://github.com/josxha/flutter_map_dragmarker. Use the pub.dev version when it's released.)
- adds native integrations to make it easier to run it the example project.

### CODE REVIEW

**Comment by pablojimpas** [comment]
Hi @josxha, thanks for taking the time to do this! I was preparing a patch with something like this myself, but I'm glad that yours is ready now.

I will test everything and get back to you with my feedback.

**Comment by josxha** [comment]
Thanks @pablojimpas! I was only able to test on android and web myself so I'm interested if other platforms work as well. (:

**Comment by pablojimpas** [comment]
Hey @josxha, is this PR ready for another full review, or should it be synced with the latest `flutter_map_dragmarker`?

**Comment by josxha** [comment]
@pablojimpas It was using dragmarkers from git. I changed it to pub.dev in https://github.com/ibrierley/flutter_map_line_editor/pull/36/commits/28592d0b086dea4d38b677a7c2db2835e9b64cc4.
Yep, ready to test now. (:

**Comment by pablojimpas** [comment]
The example app works fine on every platform that I've tested (Linux, Android, Web). The code looks good to me as well. I think this is ready to be merged and released on pub.dev if @ibrierley it's okay.

**Comment by ibrierley** [comment]
Great stuff, tests well for me. Thanks for all the work on this!

**Comment by ibrierley** [comment]
Is now on pub.dev

**Pull request merged**
