### PR TITLE
Improve example and upcycle the repo in general

### PR DESCRIPTION
**Pull request by pablojimpas**

### CODE REVIEW

**Review by ibrierley — COMMENTED** [review]
Thanks for this. There's quite a lot of files which I don't think are needed (eg all the android and ios files and example files)? The pubspec, I'm not sure I want to move to flutter_lints ^2.0.11 just yet as it will force others to have to update Flutter, but I don't mind being convinced if there is a compelling reason.

**Comment by pablojimpas** [comment]
> There's quite a lot of files which I don't think are needed (eg all the android and ios files and example files)?

Sorry about that noise, I've just removed the platform specific folders and included a notice in the README of the example to clarify how to run the example app.

> I'm not sure I want to move to flutter_lints ^2.0.11 just yet as it will force others to have to update Flutter, but I don't mind being convinced if there is a compelling reason.

AFAIK this `dev_dependency` does not affect the minimum version of flutter required. I've left both the package and the example app `pubspec.yaml`'s with the same SDK requirements `sdk: ">=2.12.0 <3.0.0"` that you had before.

**Comment by ibrierley** [comment]
I get 
Because flutter_map_line_editor depends on flutter_lints >=2.0.0 which requires SDK version >=2.17.0-0 <3.0.0, version solving failed currently (unless I update to Flutter3). 

In flutter_map we've just got flutter_lints: ">=1.0.4" which I think I'd prefer unless there's a specific reason not to currently.

The other one is "lib/main.dart:37:32: Error: Member not found: 'polyline_outlined'. Not sure where that gets pulled in from.

Apart from that, all looks good!

**Comment by pablojimpas** [comment]
> In flutter_map we've just got flutter_lints: ">=1.0.4" which I think I'd prefer unless there's a specific reason not to currently.

I've just lowered the constraints for now, but it's a good idea to keep relatively up to date with language and framework versions. In general I'll not recommend being more than two versions behind. So this is something to revisit in the future.

> The other one is "lib/main.dart:37:32: Error: Member not found: 'polyline_outlined'. Not sure where that gets pulled in from.

It seems like that particular `IconData` was introduced recently and it's not available in your version of Flutter, I've changed it to something similar but that accurate, hopefully everything it's okey now.

**Comment by ibrierley** [comment]
Thanks for the updates, all fine for me. I kind of agree with the versioning, just with things like lints, I'm less bothered (if it will force someone else to update), unless necessary. 
Thanks again!

**Pull request merged**
